export { Hero } from './Hero';
export { SocialProof } from './SocialProof';
export { Features } from './Features';
export { HowItWorks } from './HowItWorks';
export { Integrations } from './Integrations';
export { Pricing } from './Pricing';
export { Testimonials } from './Testimonials';
export { FinalCTA } from './FinalCTA';
export { Footer } from './Footer';
